### ISSUE TITLE
Dynamic dashboard

### ISSUE THREAD

**Issue by To-om** [CERT-BDF/TheHive#312]
### Request Type
Feature Request

### Problem Description
The aim of this issue is to provide dynamic dashboards, allowing users to build and configure there own dashboard.

This issue includes:
 - [x] CERT-BDF/TheHive#279: Statistics - Saved Filters
 - [x] CERT-BDF/TheHive#274: Alerts in Statistics
 - [x] CERT-BDF/TheHive#197: Export Statistics/Metrics
